version: "3.8"

services: 
  web-frontend: 
    container_name: web-frontend
    image: kova98k/wcenzije:web-frontend
    build:
      context: ..
      dockerfile: ./deploy/wcenzije-web-frontend.Dockerfile
    ports: 
      - 8001:80
  api:
    container_name: api
    image: kova98k/wcenzije:api
    build:
      context: ..
      dockerfile: ./deploy/wcenzije-api.Dockerfile
    ports: 
      - 8002:5000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=5000