name: Deploy Backend And Web Frontend

on:
  push:
    branches: ["feat/deploy-pipeline"]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/deploy

    steps:
      - name: Pull Docker-Compose and Start
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd wcenzije
            docker-compose pull
            docker-compose up -d

      - name: Check Health
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd wcenzije
            sleep 10  # Allow some time for services to initialize
            if ! docker-compose ps | grep -q 'Up'; then
                echo "One or more services failed to start"
                docker logs web-frontend
                docker logs api
                exit 1
            else    
                echo "All services are up and running"
