name: Mobile Deployment

on:
  push:
  pull_request:
    branches: [ "main", "feat/mobile-pipeline" ]
    paths: ['src/mobile/**']
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/mobile
    
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version-file: src/mobile/pubspec.yaml 
    - run: flutter --version
          
      
